spring:
  application:
     name: notification-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true