spring:
  application:
     name: notification-service
  data:
    mongodb:
      host: ${MONGO_URL}
      port: 27017
      database: ${NOTIFICATION_DB}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
server:
  port: 8002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true