spring:
  application:
     name: notification-service
  data:
     mongodb:
         host: mongo
         port: 27017
         database: notification
         username: ${MONGO_INITDB_ROOT_USERNAME}
         password: ${MONGO_INITDB_ROOT_PASSWORD}
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka server