spring:
  application:
    name: game-service
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:6033/${GAME_DB}
    username: ${GAME_DB}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
    template:
      mandatory: true
rabbitmq:
  exchange: game-exchange
  routingkey: game-routing
  queue: game-queue
server:
  port: 8001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true