spring:
  application:
    name: campaign-service
  datasource:
    url: jdbc:mysql://localhost:3306/campaign_db
    username: root
    password: leminhhoang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8004

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
