version: '3.8'
services:
  mysql-primary:
    image: mysql:8.0
    container_name: mysql-primary
    networks:
      - microservices-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_MULTIPLE_DATABASES: ${MYSQL_MULTIPLE_DATABASES}
      BINLOG_FORMAT: ROW
      GTID_MODE: ON
      ENFORCE_GTID_CONSISTENCY: ON
    ports:
      - "3306:3306"
    volumes:
      - primary-data:/var/lib/mysql
      - ./database/init-multi-mysql-databases.sh:/docker-entrypoint-initdb.d/init-multi-mysql-databases.sh
      - ./database/sql:/docker-entrypoint-initdb.d/sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --server-id=1
      --log-bin=mysql-bin
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --log-slave-updates=1

  mysql-replica-1:
    image: mysql:8.0
    restart: always
    container_name: mysql-replica-1
    networks:
      - microservices-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - replica-1-data:/var/lib/mysql
      - ./database/init-replica-replication.sql:/docker-entrypoint-initdb.d/init-replica-replication.sql
    depends_on:
      - mysql-primary
    command: >
      --default-authentication-plugin=mysql_native_password
      --server-id=2
      --log-bin=mysql-bin
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --read-only=1
      --relay-log=relay-bin
      --log-slave-updates=1

  mysql-replica-2:
    image: mysql:8.0
    container_name: mysql-replica-2
    restart: always
    networks:
      - microservices-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - replica-2-data:/var/lib/mysql
      - ./database/init-replica-replication.sql:/docker-entrypoint-initdb.d/init-replica-replication.sql
    depends_on:
      - mysql-primary
    command: >
      --default-authentication-plugin=mysql_native_password
      --server-id=3
      --log-bin=mysql-bin
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --read-only=1
      --relay-log=relay-bin
      --log-slave-updates=1

  proxysql:
    image: proxysql/proxysql:2.6.6
    container_name: proxysql
    networks:
      - microservices-network
    ports:
      - "6032:6032" # ProxySQL admin interface
      - "6033:6033" # ProxySQL MySQL interface
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql-primary
      - mysql-replica-1
      - mysql-replica-2
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./database/init-multi-mongodb-databases.sh:/docker-entrypoint-initdb.d/init-multi-mongodb-databases.sh
    ports:
      - "27017:27017"
    networks:
      - microservices-network
  discovery:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile.dev
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    env_file:
      - .env
    container_name: discovery-server
  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    networks:
      - microservices-network
    env_file:
      - .env
    container_name: api-gateway

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8005:8005"
    depends_on:
      - proxysql
      - discovery
    networks:
      - microservices-network
    env_file:
      - .env
    container_name: user-service

  brand-service:
    build:
      context: ./brand-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8003:8003"
    depends_on:
      - proxysql
      - discovery
    networks:
      - microservices-network
    env_file:
      - .env
    container_name: brand-service

  campaign-service:
    build:
      context: ./campaign-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8004:8004"
    depends_on:
      - proxysql
      - discovery
    networks:
      - microservices-network
    env_file:
      - .env
    container_name: campaign-service

#  game-service:
#      build:
#        context: ./game-service
#        dockerfile: Dockerfile.dev
#      ports:
#        - "8001:8001"
#      depends_on:
#        - mysql
#        - discovery
#      networks:
#        - microservices-network
#      env_file:
#        - .env
#      container_name: game-service
#  image-service:
#    build:
#      context: ./image-service
#      dockerfile: Dockerfile.dev
#    ports:
#      - "8007:8007"
#    depends_on:
#      - mongo
#      - discovery
#    networks:
#      - microservices-network
#    env_file:
#      - .env
#    container_name: image-service

#  rabbitmq:
#    image: rabbitmq:3.9-management
#    container_name: rabbitmq
#    restart: always
#    ports:
#      - "5672:5672" # RabbitMQ default port for AMQP
#      - "15672:15672" # Management UI
#    environment:
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
#    networks:
#      - microservices-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8002"
    depends_on:
      - discovery
      - mongo
    networks:
      - microservices-network
    env_file:
      - .env
    container_name: notification-service
#
#  voucher-service:
#      build:
#        context: ./voucher-service
#        dockerfile: Dockerfile.dev
#      restart: always
#      ports:
#        - "8006:8006"
#      depends_on:
#        - proxysql
#        - discovery
#      networks:
#        - microservices-network
#      env_file:
#        - .env
#      container_name: voucher-service

#  quizz-realtime:
#    build:
#      context: ./quizz-realtime
#      dockerfile: Dockerfile.dev
#    ports:
#      - "8007:8007"
#    depends_on:
#      - rabbitmq
#      - discovery
#    networks:
#      - microservices-network
#    env_file:
#      - .env
#    container_name: quizz-realtime
volumes:
# db-data: #uncomment this line if you want to use volume for mysql
  primary-data:
  replica-1-data:
  replica-2-data:
  mongo-data:
networks:
  microservices-network:
    driver: bridge
