hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Enable service discovery for dynamic routing
      routes:
        - id: game-info
          uri: lb://game-service
          predicates:
            - Path=/v3/game/**
        - id: game-campaign
          uri: lb://game-service
          predicates:
            - Path=/v3/game-campaigns/**
        - id: user-game-campaign
          uri: lb://game-service
          predicates:
            - Path=/v3/user-campaign-games/**
        - id: puzzle
          uri: lb://game-service
          predicates:
            - Path=/v3/puzzles/**
        - id: user-item
          uri: lb://game-service
          predicates:
            - Path=/v3/user-items/**
        - id: questions
          uri: lb://game-service
          predicates:
            - Path=/v3/questions/**
        - id: quizz
          uri: lb://game-service
          predicates:
            - Path=/v3/quizzes/**
        - id: user-answer
          uri: lb://game-service
          predicates:
            - Path=/v3/user-answers/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v3/notifications/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v3/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/v3/auth/**
        - id: voucher-service
          uri: lb://voucher-service
          predicates:
            - Path=/v3/vouchers/**
        - id: campaign-service
          uri: lb://campaign-service
          predicates:
            - Path=/v3/campaigns/**
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/v3/images/**
        - id : brand-service
          uri: lb://brand-service
          predicates:
            - Path=/v3/brands/**
        - id: branch-service
          uri: lb://brand-service
          predicates:
            - Path=/v3/branches/**
        - id: quizz-realtime
          uri: lb://quizz-realtime
          predicates:
            - Path=/v3/quizz-realtime/**
        #authentication some routes
        - id: get-all-users
          uri: lb://user-service
          predicates:
            - Path=/v3/users
            - Method=GET
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5173/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/ # Eureka server

server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:your-secret-key}