spring:
  application:
    name: image-service
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: 27017
      database: ${IMAGE_DB}
server:
  port: 8007

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true