spring:
  application:
    name: image-service
  data:
    mongodb:
      uri: mongodb://root:123456@mongo1:27017,mongo2:27018,mongo3:27019/image_db?replicaSet=rs0&authSource=admin

server:
  port: 8007

redis:
  host: cache
  port: 6379
  password: ${REDIS_PASSWORD}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
