spring:
  application:
    name: voucher-service
  datasource:
    url: jdbc:mysql://localhost:3306/voucher_db
    username: root
    password: leminhhoang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true

server:
  port: 8006

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true